apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileservice
  labels:
    app: fileservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileservice
  template:
    metadata:
      labels:
        app: fileservice
    spec:
      containers:
        - name: fileservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ROOT_PATH
              value: "{{ .Values.rootPath }}"
          volumeMounts:
            - name: data
              mountPath: {{ .Values.rootPath }}
      volumes:
        - name: data
          emptyDir: {}